name: update inputs

on:
  schedule:
    # run every saturday
    - cron: "0 0 * * 6"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-lock:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ github.token }}

      - uses: DeterminateSystems/update-flake-lock@v19
        id: update
        with:
          commit-msg: "flake: update inputs"
          pr-title: "flake: update all inputs"
          nix-options: "--accept-flake-config"
          token: ${{ github.token }}

      - name: auto-merge pull request
        run: gh pr merge --auto --rebase "$PR_ID"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PR_ID: ${{ steps.update.outputs.pull-request-number }}
